# Site settings
name: Agnish Chakraborty
title: Agnish Chakraborty | Agnishc
description: This site was created to showcase my chatbot, blockchain and node backend projects. I am a software developer with 2+ years of experience. To hire me, you can reach out to me with the given contact list.
url: https://agnishchakraborty.com/
baseurl: ""
email: agnishc.dev@gmail.com
cover: https://agnishchakraborty.com/img/cover.png
logo: https://agnishchakraborty.com/img/emojis/technologist.png
resume: https://agnishchakraborty.com/resume.pdf
social:
  - title: email
    url: mailto:agnishc.dev@gmail.com
  - title: upwork
    url: https://www.upwork.com/o/profiles/users/_~01edb2a70a4b8bf4d6/
  - title: twitter
    url: https://twitter.com/agnish_cc
  - title: skype
    url: https://join.skype.com/invite/cRjo8wcSFBye
  - title: github
    url: https://github.com/agnishcc
  - title: linkedin
    url: https://www.linkedin.com/in/agnish-chakraborty-7b5a00135/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
